### ISSUE TITLE
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-apache_kafka#kafka_topics_partitions

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-docs/EventStreams#1]
Hi

![image](https://user-images.githubusercontent.com/23421829/158559869-70ce650e-c424-4e14-b8d3-b48875c374b1.png)

**Comment by karen-rodgers** [comment]
Many thanks for reporting. I've now fixed the issue.

**Comment by andrealang** [comment]
Can someone please close this issue, as it's been fixed.

**Comment by andrealang** [comment]
@jxadro Could you please close this issue? Many thanks!
