### ISSUE TITLE
<GSSC>Copy to clipboard icon missing

### ISSUE THREAD

**Issue by xiepingp** [ibm-cloud-docs/EventStreams#17]
Commands should have a "copy to clipboard" icon next to them. Below pages have very many commands without the Copy to clipboard icon which is inconvenient for people who wants to copy these commands:

https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-restrict_access
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-consuming_messages
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-producing_messages
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-ES_schema_registry
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-ksql_using
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-kafka_java_using
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-restrictions
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-report_problem
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-data_security
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-connecting_classic
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-rest_using_classic
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-kafka_java_migrating_classic
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-restrictions_classic
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-migrate_dedicated_enterprise

Screenshots please refer to below:
![K5 no Copy button 01](https://user-images.githubusercontent.com/63960906/88362538-7094eb00-cdaf-11ea-9426-42355ead5619.png)
![K5 no Copy button 02](https://user-images.githubusercontent.com/63960906/88362544-75599f00-cdaf-11ea-92db-4d3a9e901f07.png)
![K5 no Copy button 03](https://user-images.githubusercontent.com/63960906/88362547-768acc00-cdaf-11ea-9504-e32c350bbf82.png)
![K5 no Copy button 04](https://user-images.githubusercontent.com/63960906/88362549-77bbf900-cdaf-11ea-81da-3347b94a555a.png)
![K5 no Copy button 05](https://user-images.githubusercontent.com/63960906/88362553-7a1e5300-cdaf-11ea-8643-94c18107682b.png)

**Comment by Yogendra0Sharma** [comment]
HI, @xiepingp  Can I take this issue?

**Comment by xiepingp** [comment]
Sure @Yogendra0Sharma! Thanks for taking it 😄

**Comment by andrealang** [comment]
This seems to be fixed, please close. @xiepingp @Yogendra0Sharma
