### ISSUE TITLE
Important information is commented out; and not showing on document.

### ISSUE THREAD

**Issue by ericqqqqq** [ibm-cloud-docs/EventStreams#18]
Hi, is this [part](https://github.com/ibm-cloud-docs/EventStreams/blame/master/eventstreams141.md#L115-L127) of information true? I am asking this question because this piece of information gets commented out.

If it's true, I think it is very important and should not to be commented out.

Thanks.

**Comment by mimaison** [comment]
This information has been removed because it's hard to keep up to date. We instead listed the client requirements in https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-kafka_using. Before selecting a client, you should check it provides the required capabilities.

**Comment by andrealang** [comment]
@cjcarpen This issue has been taken care of, could you please close? Many thanks!
