### ISSUE TITLE
<GSSC>Headings are missing on the right panel

### ISSUE THREAD

**Issue by xiepingp** [ibm-cloud-docs/EventStreams#19]
Headings are missing on the right panel:
Page locations: https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-kafka_java_using
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-choose_api_classic
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-bridges
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-cloud_object_storage_bridge

![headings missing](https://user-images.githubusercontent.com/63960906/90849421-c5715480-e3a1-11ea-8bc2-f6cfa44e0ca7.png)

![headings missing - 2](https://user-images.githubusercontent.com/63960906/90857416-aa5d0f80-e3b6-11ea-9729-753ac1308270.png)

![headings missing - 3](https://user-images.githubusercontent.com/63960906/90857916-b5fd0600-e3b7-11ea-9bd1-a7312771f307.png)

![headings missing - 4](https://user-images.githubusercontent.com/63960906/90858193-4cc9c280-e3b8-11ea-93bf-e7f5e5aa6137.png)

**Comment by andrealang** [comment]
@cjcarpen I fixed this issue, could you please close it? Many thanks!
