### ISSUE TITLE
Images are not visible. Looks like some issue in Markup syntax.

### ISSUE THREAD

**Issue by simbu21** [ibm-cloud-docs/EventStreams#2]
![image](https://user-images.githubusercontent.com/325134/168790331-4503d1b6-3b4e-4aaf-8ef5-ee1548ebafab.png)
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-apache_kafka#kafka_topics_partitions

**Comment by karen-rodgers** [comment]
Many thanks for reporting. I've now fixed the issue.

**Comment by andrealang** [comment]
This issue can be closed pleased @simbu21 @edoardocomar @Charlie-Martin (sorry, don't know who can close, as I don't have the option to).
