### ISSUE TITLE
French EventStream documentation not up to date

### ISSUE THREAD

**Issue by waewoo** [ibm-cloud-docs/EventStreams#20]
Hello,

In the EventStream document, the French documentation is not at all up to date with the English documentation.

For example, and these are not the only ones, these parts are not up to date (see missing) in the French part:

https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-restrict_access
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-managing_encryption
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-ES_scaling_capacity
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-mirroring_setup

So can you make sure that the documentation in French is aligned with the documentation in English ?

Thank you

**Comment by mimaison** [comment]
Hi @waewoo,

Translations are only updated once per quarter, so they might not be completely up to date if a topic has changed recently. We recommend up check the English version for the latest updates.

Thanks

**Comment by andrealang** [comment]
@cjcarpen This issue can be closed pleased. Thanks a lot!
