### ISSUE TITLE
TLS Security not up to date

### ISSUE THREAD

**Issue by waewoo** [ibm-cloud-docs/EventStreams#21]
Hello, 

The following documentation only talks about TLS V1.2 while EventStream allows to communicate in TLS V1.3
https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-data_security

Can you update the documentation specified the associated cipher.

Thank you

**Comment by mimaison** [comment]
Thank you for reporting this inconsistency. This is currently being addressed and the page will be updated soon.

**Comment by mimaison** [comment]
The documentation has been updated: https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-data_security

**Comment by waewoo** [comment]
Thanks Mickael ! ;)
