### ISSUE TITLE
Writer role permission

### ISSUE THREAD

**Issue by mikkolaakko** [ibm-cloud-docs/EventStreams#24]
It is not obvious that a writer role has also permission to consume from a topic. Personally I think you should assign both reader and writer roles in order to produce and consume from a topic. Currently all producers can also consume messages that other producers have published to the topic. This may be an issue if messages contain confidential information. A workaround is to create a topic for each producer.

**Comment by andrealang** [comment]
@mimaison Could you please check if we need to document sth. regarding this issue? Otherwise, we need to move it to the docs repo, as all issues here have to be fixed/closed asap, as the repo needs to be deleted and re-created due to technical issues. Thank you!

**Comment by Charlie-Martin** [comment]
Hi, thanks for the comment. This behaviour for the accumulation of permissions is part of the built-in functionality of the IBM Cloud IAM service and as such is inherited by all services within IBM Cloud. Further info: https://cloud.ibm.com/docs/account?topic=account-userroles#service_access_roles
