### ISSUE TITLE
Incorrect link to wildcarding

### ISSUE THREAD

**Issue by bogeyman61** [ibm-cloud-docs/EventStreams#25]
Several links referenced in topic: [Managing access to your Event Streams](https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-security) resources are incorrect and result in Page not found: 

- For more information about IAM, see [IBM Cloud Identity and Access Management](https://cloud.ibm.com/docs/iam?topic=iam-iamoverview#iamoverview).

- For more information, see [Assigning access by using wildcard policies](https://cloud.ibm.com/docs/iam?topic=iam-wildcard)

**Comment by andrealang** [comment]
@cjcarpen Both links are fixed now, please close this issue. Thank you!
