### ISSUE TITLE
Version info in the documentation

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/EventStreams#28]
Customer Legic asked for Version information as they plan DR in Paris, where event streams is not available as a service. Therefore they need to install Kafka on Roks and want to sync the instances. 

Therfore it would help if we could provide an info on which underlaying Kafka version EventStreams is running.

**Comment by andrealang** [comment]
@mimaison Could you please take a look at this issue and help me to update the doc accordingly? Many thanks!

**Comment by tschrenk-corp** [comment]
question answered.
