### ISSUE TITLE
Formatting issue for table in EventStreams-metrics#metric_costs

### ISSUE THREAD

**Issue by patmc2go** [ibm-cloud-docs/EventStreams#30]
Topic: https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-metrics#metric_costs

I think you expected we would see this:
![image](https://user-images.githubusercontent.com/12019963/134980152-d1a0116e-eebf-4cf4-8ff8-144906d62457.png)

Vs this:
`| Plan | Topics | Number of time series | Monthly cost | |------------------|--------------|------------------| | Lite | 1 |1 x 2 + 5 = 7 | $0.08 x 7 = $0.56 | | Standard | 1 | 1 x 2 + 5 = 7 | $0.08 x 7 = $0.56 | | | 10 | 10 x 2 + 5 = 25 | $0.08 x 25 = $2 | | | 100 | 100 x 2 + 5 = 205 | $0.08 x 205 = $16.40 | | Enterprise | 1 | 1 x 2 + 16 = 18 | $0.08 x 18 = $1.44 | | | 10 | 10 x 2 + 16 = 36 | $0.08 x 36 = $2.88 | | | 100 | 100 x 2 + 16 = 216 | $0.08 x 216 = $17.28 | | | 1000 | 1000 x 2 + 16 = 2016 | $0.08 x 2016 = $161.28 | | | 3000 | 3000 x 2 + 16 = 6016 | $0.08 x 6016 = $481.28 | `

To see the table in pure GIT I broke it up into multiple lines and added a missing column indicator:
```
| Plan | Topics | Number of time series | Monthly cost | 
|------------------|--------------|------------------|------------------| 
| Lite | 1 |1 x 2 + 5 = 7 | $0.08 x 7 = $0.56 | 
| Standard | 1 | 1 x 2 + 5 = 7 | $0.08 x 7 = $0.56 | 
| | 10 | 10 x 2 + 5 = 25 | $0.08 x 25 = $2 | 
| | 100 | 100 x 2 + 5 = 205 | $0.08 x 205 = $16.40 | 
| Enterprise | 1 | 1 x 2 + 16 = 18 | $0.08 x 18 = $1.44 | 
| | 10 | 10 x 2 + 16 = 36 | $0.08 x 36 = $2.88 | 
| | 100 | 100 x 2 + 16 = 216 | $0.08 x 216 = $17.28 | 
| | 1000 | 1000 x 2 + 16 = 2016 | $0.08 x 2016 = $161.28 | 
| | 3000 | 3000 x 2 + 16 = 6016 | $0.08 x 6016 = $481.28 |
```

**Comment by karen-rodgers** [comment]
@patmc2go many thanks for letting me know about this. Fixed now! https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-metrics#metric_costs
