### ISSUE TITLE
Typo in Getting Started Tutorial

### ISSUE THREAD

**Issue by EdMoffatt** [ibm-cloud-docs/EventStreams#31]
In this tutorial: https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-getting-started

Step 4 has you start the consuming app, and the command to copy/paste is correctly formatted:

```
java -jar ./build/libs/kafka-java-console-sample-2.0.jar \
<kafka_brokers_sasl> <api_key> -consumer
```

Step 6 has you start the producer, but the command to copy contains a line break without a backslash, so you get an error when you paste it into the terminal (for the missing args, which get submitted as a separate command).

```
java -jar ./build/libs/kafka-java-console-sample-2.0.jar
 <kafka_brokers_sasl> <api_key> -producer
```

That one should be:

```
java -jar ./build/libs/kafka-java-console-sample-2.0.jar \
<kafka_brokers_sasl> <api_key> -producer
```

**Comment by andrealang** [comment]
@cjcarpen This issue has been fixed, please close. Many thanks!
